version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "80:5000"
    volumes:
      - ./server:/server
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
